"""
Windchill Config — YAML Loader & Parser
========================================
Loads a company YAML config file and returns a validated, normalized
dictionary that the generators can consume.
"""

import yaml
from pathlib import Path
from typing import Any

from .model import ROLES, PREFERENCES, ASSOCIATION_TYPES


def load_config(path: str | Path) -> dict[str, Any]:
    """Load and normalize a YAML company config file."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    with open(path, "r") as f:
        raw = yaml.safe_load(f)

    if not raw:
        raise ValueError("Config file is empty")

    return _normalize(raw)


def _normalize(raw: dict) -> dict:
    """Fill in defaults and normalize the raw YAML structure."""
    config = {}

    # ─── Company ──────────────────────────────────────────────
    company = raw.get("company", {})
    config["company"] = {
        "name": company.get("name", ""),
        "org": company.get("org", ""),
        "site": company.get("site", ""),
        "context_level": company.get("context_level", "organization"),
        "lock_preferences": company.get("lock_preferences", True),
        "use_flexible_change": company.get("use_flexible_change", True),
    }

    # ─── Groups ───────────────────────────────────────────────
    config["groups"] = []
    for g in raw.get("groups", []):
        config["groups"].append({
            "id": g.get("id", ""),
            "name": g.get("name", ""),
            "description": g.get("description", ""),
        })

    # ─── People ───────────────────────────────────────────────
    config["people"] = []
    for p in raw.get("people", []):
        config["people"].append({
            "id": p.get("id", ""),
            "name": p.get("name", ""),
            "username": p.get("username", ""),
            "email": p.get("email", ""),
            "group": p.get("group", ""),
        })

    # Index people by ID for quick lookup
    config["_people_index"] = {p["id"]: p for p in config["people"]}

    # ─── Role Assignments ─────────────────────────────────────
    config["roles"] = {}
    raw_roles = raw.get("roles", {})
    for role_id in ROLES:
        assigned = raw_roles.get(role_id, [])
        if isinstance(assigned, str):
            assigned = [assigned]
        config["roles"][role_id] = assigned

    # ─── Preferences ──────────────────────────────────────────
    config["preferences"] = {}
    raw_prefs = raw.get("preferences", {})
    for pref_key, pref_def in PREFERENCES.items():
        val = raw_prefs.get(pref_key, pref_def.default)
        config["preferences"][pref_key] = str(val)

    # ─── Associations ─────────────────────────────────────────
    config["associations"] = {}
    raw_assoc = raw.get("associations", {})
    for assoc_key, assoc_def in ASSOCIATION_TYPES.items():
        user_assoc = raw_assoc.get(assoc_key, {})
        config["associations"][assoc_key] = {
            "enabled": user_assoc.get("enabled", assoc_def["standard"]),
            "cardinality": user_assoc.get("cardinality", "many:1"),
            "owning_role": user_assoc.get("owning_role", "none"),
            "required_role": user_assoc.get("required_role", "none"),
        }

    # ─── Business Rules ───────────────────────────────────────
    raw_rules = raw.get("business_rules", {})
    company_prefix = config["company"]["name"].replace(" ", "_").upper()
    config["business_rules"] = {
        "rule_set_name": raw_rules.get("rule_set_name", f"{company_prefix}_PRE_RELEASE"),
        "rules": raw_rules.get("rules", [
            {"key": f"{company_prefix}_CHECKOUT_RULE", "selector": "CHECKOUT_RULE",
             "description": "Fails if changeable is checked out", "block_number": 1},
            {"key": f"{company_prefix}_RELEASE_TARGET_RULE", "selector": "RELEASE_TARGET_RULE",
             "description": "Validates change transition", "block_number": 10},
        ]),
    }

    # ─── Custom Attributes ────────────────────────────────────
    config["custom_attributes"] = raw.get("custom_attributes", []) or []

    return config


def save_config(config: dict, path: str | Path) -> None:
    """Write a config dict back to YAML (for the wizard)."""
    path = Path(path)

    # Remove internal index before saving
    output = {k: v for k, v in config.items() if not k.startswith("_")}

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("# ═══════════════════════════════════════════════════════════════════\n")
        f.write(f"# Windchill Change Management — Company Configuration\n")
        f.write(f"# Company: {config['company']['name']}\n")
        f.write("# Generated by: wc-config wizard\n")
        f.write("# ═══════════════════════════════════════════════════════════════════\n\n")
        yaml.dump(output, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
